
{{- if (.Values.httproute).enabled -}}
{{- $applicationNameTpl := include "application.name" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ template "application.name" . }}
  namespace: {{ include "application.namespace" . }}
  labels:
  {{- include "application.labels" $ | nindent 4 }}
{{- if .Values.httproute.additionalLabels }}
{{ toYaml .Values.httproute.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.httproute.annotations }}
  annotations:
{{ toYaml .Values.httproute.annotations | indent 4 }}
{{- end }}
spec:
  parentRefs:
  {{- toYaml .Values.httproute.parentRefs | nindent 3 }}
  hostnames:
  {{- toYaml .Values.httproute.hostnames | nindent 3 }}
  rules:
  {{- toYaml .Values.httproute.rules | nindent 3 }}
---
{{- end }}